<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp();

        // The PHP suite does not test the frontend build and must not require one.
        // public/build is gitignored and generated by the image's assets stage, so a
        // fresh clone — CI, or any checkout that has not run `npm run build` — has no
        // manifest, and every view reaching @vite throws:
        //
        //   Illuminate\Foundation\ViteManifestNotFoundException:
        //     Vite manifest not found at: public/build/manifest.json
        //
        // That used to be masked by a committed manifest.json, which was worse than
        // this: it named 32 assets nobody shipped, so it satisfied the suite while
        // the storefront 404'd every one of them in production. withoutVite() is
        // Laravel's supported "render the views, skip the asset tags" — no test here
        // asserts on asset URLs, and the assets are verified where they actually
        // matter, in the image (see the docker job's smoke step).
        $this->withoutVite();
    }
}
