apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-laravel-ingress
  namespace: ecommerce-laravel
  labels:
    app.kubernetes.io/name: ecommerce-laravel
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
    - host: "${APP_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-laravel-app
                port:
                  number: 80
          - path: /app/ws
            pathType: Prefix
            backend:
              service:
                name: reverb-service
                port:
                  number: 8080
  tls:
    - hosts:
        - "${APP_DOMAIN}"
      secretName: ecommerce-laravel-tls
