apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecommerce-laravel-network-policy
  namespace: ecommerce-laravel
  labels:
    app.kubernetes.io/name: ecommerce-laravel
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ecommerce-laravel
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - from:
        - namespaceSelector:
            matchLabels:
              name: ecommerce-laravel
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8080
  egress:
    - ports:
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: UDP
          port: 53
