apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-laravel-secret
  namespace: ecommerce-laravel
  labels:
    app.kubernetes.io/name: ecommerce-laravel
type: Opaque
stringData:
  APP_KEY: ""
  DB_HOST: ""
  DB_DATABASE: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  REDIS_HOST: ""
  REDIS_PASSWORD: ""
  MAIL_HOST: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  STRIPE_KEY: ""
  STRIPE_SECRET: ""
  REVERB_APP_ID: ""
  REVERB_APP_KEY: ""
  REVERB_APP_SECRET: ""
