[supervisord]
nodaemon=true
user=%(ENV_USER)s
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:reverb]
process_name=%(program_name)s_%(process_num)02d
command=php %(ENV_ROOT)s/artisan reverb:start --host=0.0.0.0 --port=%(ENV_REVERB_PORT)s --no-interaction
user=%(ENV_USER)s
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopwaitsecs=60
