apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-laravel

resources:
  - ../../
  - hpa.yaml

patches:
  - target:
      kind: Deployment
      name: ecommerce-laravel-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: ecommerce-laravel-ingress
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-prod
      - op: replace
        path: /spec/tls
        value:
          - hosts:
              - "${APP_DOMAIN}"
            secretName: ecommerce-laravel-tls

configMapGenerator:
  - name: ecommerce-laravel-config
    behavior: merge
    literals:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=warning
